ab :1st_place_medal: 🥇
ab :2nd_place_medal: 🥈
ab :3rd_place_medal: 🥉
ab :8ball: 🎱
ab :art: 🎨
ab :badminton: 🏸
ab :balloon: 🎈
ab :bamboo: 🎍
ab :baseball: ⚾
ab :basketball: 🏀
ab :black_joker: 🃏
ab :bowling: 🎳
ab :boxing_glove: 🥊
ab :chess_pawn: ♟️
ab :christmas_tree: 🎄
ab :clubs: ♣️
ab :confetti_ball: 🎊
ab :cricket_game: 🏏
ab :crystal_ball: 🔮
ab :curling_stone: 🥌
ab :dart: 🎯
ab :diamonds: ♦️
ab :diving_mask: 🤿
ab :dolls: 🎎
ab :field_hockey: 🏑
ab :firecracker: 🧨
ab :fireworks: 🎆
ab :fishing_pole_and_fish: 🎣
ab :flags: 🎏
ab :flower_playing_cards: 🎴
ab :flying_disc: 🥏
ab :football: 🏈
ab :framed_picture: 🖼️
ab :game_die: 🎲
ab :gift: 🎁
ab :goal_net: 🥅
ab :golf: ⛳
ab :hearts: ♥️
ab :ice_hockey: 🏒
ab :ice_skate: ⛸️
ab :jack_o_lantern: 🎃
ab :jigsaw: 🧩
ab :joystick: 🕹️
ab :kite: 🪁
ab :knot: 🪢
ab :lacrosse: 🥍
ab :magic_wand: 🪄
ab :mahjong: 🀄
ab :martial_arts_uniform: 🥋
ab :medal_military: 🎖️
ab :medal_sports: 🏅
ab :nazar_amulet: 🧿
ab :nesting_dolls: 🪆
ab :performing_arts: 🎭
ab :pinata: 🪅
ab :ping_pong: 🏓
ab :red_envelope: 🧧
ab :reminder_ribbon: 🎗️
ab :ribbon: 🎀
ab :rice_scene: 🎑
ab :rugby_football: 🏉
ab :running_shirt_with_sash: 🎽
ab :sewing_needle: 🪡
ab :ski: 🎿
ab :sled: 🛷
ab :slot_machine: 🎰
ab :soccer: ⚽
ab :softball: 🥎
ab :spades: ♠️
ab :sparkler: 🎇
ab :sparkles: ✨
ab :tada: 🎉
ab :tanabata_tree: 🎋
ab :teddy_bear: 🧸
ab :tennis: 🎾
ab :thread: 🧵
ab :ticket: 🎫
ab :tickets: 🎟️
ab :trophy: 🏆
ab :video_game: 🎮
ab :volleyball: 🏐
ab :wind_chime: 🎐
ab :yarn: 🧶
ab :yo_yo: 🪀