ab :ant: 🐜
ab :baby_chick: 🐤
ab :badger: 🦡
ab :bat: 🦇
ab :bear: 🐻
ab :beaver: 🦫
ab :bee: 🐝
ab :beetle: 🪲
ab :bird: 🐦
ab :bison: 🦬
ab :black_cat: 🐈‍⬛
ab :blossom: 🌼
ab :blowfish: 🐡
ab :boar: 🐗
ab :bouquet: 💐
ab :bug: 🐛
ab :butterfly: 🦋
ab :cactus: 🌵
ab :camel: 🐫
ab :cat: 🐱
ab :cat2: 🐈
ab :cherry_blossom: 🌸
ab :chicken: 🐔
ab :chipmunk: 🐿️
ab :cockroach: 🪳
ab :cow: 🐮
ab :cow2: 🐄
ab :cricket: 🦗
ab :crocodile: 🐊
ab :deciduous_tree: 🌳
ab :deer: 🦌
ab :dodo: 🦤
ab :dog: 🐶
ab :dog2: 🐕
ab :dolphin: 🐬
ab :dove: 🕊️
ab :dragon: 🐉
ab :dragon_face: 🐲
ab :dromedary_camel: 🐪
ab :duck: 🦆
ab :eagle: 🦅
ab :ear_of_rice: 🌾
ab :elephant: 🐘
ab :evergreen_tree: 🌲
ab :fallen_leaf: 🍂
ab :feather: 🪶
ab :feet: 🐾
ab :fish: 🐟
ab :flamingo: 🦩
ab :flipper: 🐬
ab :fly: 🪰
ab :four_leaf_clover: 🍀
ab :fox_face: 🦊
ab :frog: 🐸
ab :giraffe: 🦒
ab :goat: 🐐
ab :gorilla: 🦍
ab :guide_dog: 🦮
ab :hamster: 🐹
ab :hatched_chick: 🐥
ab :hatching_chick: 🐣
ab :hedgehog: 🦔
ab :herb: 🌿
ab :hibiscus: 🌺
ab :hippopotamus: 🦛
ab :honeybee: 🐝
ab :horse: 🐴
ab :kangaroo: 🦘
ab :koala: 🐨
ab :lady_beetle: 🐞
ab :leaves: 🍃
ab :leopard: 🐆
ab :lion: 🦁
ab :lizard: 🦎
ab :llama: 🦙
ab :mammoth: 🦣
ab :maple_leaf: 🍁
ab :microbe: 🦠
ab :monkey: 🐒
ab :monkey_face: 🐵
ab :mosquito: 🦟
ab :mouse: 🐭
ab :mouse2: 🐁
ab :octopus: 🐙
ab :orangutan: 🦧
ab :otter: 🦦
ab :owl: 🦉
ab :ox: 🐂
ab :palm_tree: 🌴
ab :panda_face: 🐼
ab :parrot: 🦜
ab :paw_prints: 🐾
ab :peacock: 🦚
ab :penguin: 🐧
ab :pig: 🐷
ab :pig2: 🐖
ab :pig_nose: 🐽
ab :polar_bear: 🐻‍❄️
ab :poodle: 🐩
ab :potted_plant: 🪴
ab :rabbit: 🐰
ab :rabbit2: 🐇
ab :raccoon: 🦝
ab :racehorse: 🐎
ab :ram: 🐏
ab :rat: 🐀
ab :rhinoceros: 🦏
ab :rooster: 🐓
ab :rose: 🌹
ab :rosette: 🏵️
ab :sauropod: 🦕
ab :scorpion: 🦂
ab :seal: 🦭
ab :seedling: 🌱
ab :service_dog: 🐕‍🦺
ab :shamrock: ☘️
ab :shark: 🦈
ab :sheep: 🐑
ab :shell: 🐚
ab :skunk: 🦨
ab :sloth: 🦥
ab :snail: 🐌
ab :snake: 🐍
ab :spider: 🕷️
ab :spider_web: 🕸️
ab :sunflower: 🌻
ab :swan: 🦢
ab :t-rex: 🦖
ab :tiger: 🐯
ab :tiger2: 🐅
ab :tropical_fish: 🐠
ab :tulip: 🌷
ab :turkey: 🦃
ab :turtle: 🐢
ab :unicorn: 🦄
ab :water_buffalo: 🐃
ab :whale: 🐳
ab :whale2: 🐋
ab :white_flower: 💮
ab :wilted_flower: 🥀
ab :wolf: 🐺
ab :worm: 🪱
ab :zebra: 🦓