ab :afghanistan: 🇦🇫
ab :aland_islands: 🇦🇽
ab :albania: 🇦🇱
ab :algeria: 🇩🇿
ab :american_samoa: 🇦🇸
ab :andorra: 🇦🇩
ab :angola: 🇦🇴
ab :anguilla: 🇦🇮
ab :antarctica: 🇦🇶
ab :antigua_barbuda: 🇦🇬
ab :argentina: 🇦🇷
ab :armenia: 🇦🇲
ab :aruba: 🇦🇼
ab :ascension_island: 🇦🇨
ab :australia: 🇦🇺
ab :austria: 🇦🇹
ab :azerbaijan: 🇦🇿
ab :bahamas: 🇧🇸
ab :bahrain: 🇧🇭
ab :bangladesh: 🇧🇩
ab :barbados: 🇧🇧
ab :belarus: 🇧🇾
ab :belgium: 🇧🇪
ab :belize: 🇧🇿
ab :benin: 🇧🇯
ab :bermuda: 🇧🇲
ab :bhutan: 🇧🇹
ab :black_flag: 🏴
ab :bolivia: 🇧🇴
ab :bosnia_herzegovina: 🇧🇦
ab :botswana: 🇧🇼
ab :bouvet_island: 🇧🇻
ab :brazil: 🇧🇷
ab :british_indian_ocean_territory: 🇮🇴
ab :british_virgin_islands: 🇻🇬
ab :brunei: 🇧🇳
ab :bulgaria: 🇧🇬
ab :burkina_faso: 🇧🇫
ab :burundi: 🇧🇮
ab :cambodia: 🇰🇭
ab :cameroon: 🇨🇲
ab :canada: 🇨🇦
ab :canary_islands: 🇮🇨
ab :cape_verde: 🇨🇻
ab :caribbean_netherlands: 🇧🇶
ab :cayman_islands: 🇰🇾
ab :central_african_republic: 🇨🇫
ab :ceuta_melilla: 🇪🇦
ab :chad: 🇹🇩
ab :checkered_flag: 🏁
ab :chile: 🇨🇱
ab :christmas_island: 🇨🇽
ab :clipperton_island: 🇨🇵
ab :cn: 🇨🇳
ab :cocos_islands: 🇨🇨
ab :colombia: 🇨🇴
ab :comoros: 🇰🇲
ab :congo_brazzaville: 🇨🇬
ab :congo_kinshasa: 🇨🇩
ab :cook_islands: 🇨🇰
ab :costa_rica: 🇨🇷
ab :cote_divoire: 🇨🇮
ab :croatia: 🇭🇷
ab :crossed_flags: 🎌
ab :cuba: 🇨🇺
ab :curacao: 🇨🇼
ab :cyprus: 🇨🇾
ab :czech_republic: 🇨🇿
ab :de: 🇩🇪
ab :denmark: 🇩🇰
ab :diego_garcia: 🇩🇬
ab :djibouti: 🇩🇯
ab :dominica: 🇩🇲
ab :dominican_republic: 🇩🇴
ab :ecuador: 🇪🇨
ab :egypt: 🇪🇬
ab :el_salvador: 🇸🇻
ab :england: 🏴󠁧󠁢󠁥󠁮󠁧󠁿
ab :equatorial_guinea: 🇬🇶
ab :eritrea: 🇪🇷
ab :es: 🇪🇸
ab :estonia: 🇪🇪
ab :ethiopia: 🇪🇹
ab :eu: 🇪🇺
ab :european_union: 🇪🇺
ab :falkland_islands: 🇫🇰
ab :faroe_islands: 🇫🇴
ab :fiji: 🇫🇯
ab :finland: 🇫🇮
ab :fr: 🇫🇷
ab :french_guiana: 🇬🇫
ab :french_polynesia: 🇵🇫
ab :french_southern_territories: 🇹🇫
ab :gabon: 🇬🇦
ab :gambia: 🇬🇲
ab :gb: 🇬🇧
ab :georgia: 🇬🇪
ab :ghana: 🇬🇭
ab :gibraltar: 🇬🇮
ab :greece: 🇬🇷
ab :greenland: 🇬🇱
ab :grenada: 🇬🇩
ab :guadeloupe: 🇬🇵
ab :guam: 🇬🇺
ab :guatemala: 🇬🇹
ab :guernsey: 🇬🇬
ab :guinea: 🇬🇳
ab :guinea_bissau: 🇬🇼
ab :guyana: 🇬🇾
ab :haiti: 🇭🇹
ab :heard_mcdonald_islands: 🇭🇲
ab :honduras: 🇭🇳
ab :hong_kong: 🇭🇰
ab :hungary: 🇭🇺
ab :iceland: 🇮🇸
ab :india: 🇮🇳
ab :indonesia: 🇮🇩
ab :iran: 🇮🇷
ab :iraq: 🇮🇶
ab :ireland: 🇮🇪
ab :isle_of_man: 🇮🇲
ab :israel: 🇮🇱
ab :it: 🇮🇹
ab :jamaica: 🇯🇲
ab :jersey: 🇯🇪
ab :jordan: 🇯🇴
ab :jp: 🇯🇵
ab :kazakhstan: 🇰🇿
ab :kenya: 🇰🇪
ab :kiribati: 🇰🇮
ab :kosovo: 🇽🇰
ab :kr: 🇰🇷
ab :kuwait: 🇰🇼
ab :kyrgyzstan: 🇰🇬
ab :laos: 🇱🇦
ab :latvia: 🇱🇻
ab :lebanon: 🇱🇧
ab :lesotho: 🇱🇸
ab :liberia: 🇱🇷
ab :libya: 🇱🇾
ab :liechtenstein: 🇱🇮
ab :lithuania: 🇱🇹
ab :luxembourg: 🇱🇺
ab :macau: 🇲🇴
ab :macedonia: 🇲🇰
ab :madagascar: 🇲🇬
ab :malawi: 🇲🇼
ab :malaysia: 🇲🇾
ab :maldives: 🇲🇻
ab :mali: 🇲🇱
ab :malta: 🇲🇹
ab :marshall_islands: 🇲🇭
ab :martinique: 🇲🇶
ab :mauritania: 🇲🇷
ab :mauritius: 🇲🇺
ab :mayotte: 🇾🇹
ab :mexico: 🇲🇽
ab :micronesia: 🇫🇲
ab :moldova: 🇲🇩
ab :monaco: 🇲🇨
ab :mongolia: 🇲🇳
ab :montenegro: 🇲🇪
ab :montserrat: 🇲🇸
ab :morocco: 🇲🇦
ab :mozambique: 🇲🇿
ab :myanmar: 🇲🇲
ab :namibia: 🇳🇦
ab :nauru: 🇳🇷
ab :nepal: 🇳🇵
ab :netherlands: 🇳🇱
ab :new_caledonia: 🇳🇨
ab :new_zealand: 🇳🇿
ab :nicaragua: 🇳🇮
ab :niger: 🇳🇪
ab :nigeria: 🇳🇬
ab :niue: 🇳🇺
ab :norfolk_island: 🇳🇫
ab :northern_mariana_islands: 🇲🇵
ab :north_korea: 🇰🇵
ab :norway: 🇳🇴
ab :oman: 🇴🇲
ab :pakistan: 🇵🇰
ab :palau: 🇵🇼
ab :palestinian_territories: 🇵🇸
ab :panama: 🇵🇦
ab :papua_new_guinea: 🇵🇬
ab :paraguay: 🇵🇾
ab :peru: 🇵🇪
ab :philippines: 🇵🇭
ab :pirate_flag: 🏴‍☠️
ab :pitcairn_islands: 🇵🇳
ab :poland: 🇵🇱
ab :portugal: 🇵🇹
ab :puerto_rico: 🇵🇷
ab :qatar: 🇶🇦
ab :rainbow_flag: 🏳️‍🌈
ab :reunion: 🇷🇪
ab :romania: 🇷🇴
ab :ru: 🇷🇺
ab :rwanda: 🇷🇼
ab :samoa: 🇼🇸
ab :san_marino: 🇸🇲
ab :sao_tome_principe: 🇸🇹
ab :saudi_arabia: 🇸🇦
ab :scotland: 🏴󠁧󠁢󠁳󠁣󠁴󠁿
ab :senegal: 🇸🇳
ab :serbia: 🇷🇸
ab :seychelles: 🇸🇨
ab :sierra_leone: 🇸🇱
ab :singapore: 🇸🇬
ab :sint_maarten: 🇸🇽
ab :slovakia: 🇸🇰
ab :slovenia: 🇸🇮
ab :solomon_islands: 🇸🇧
ab :somalia: 🇸🇴
ab :south_africa: 🇿🇦
ab :south_georgia_south_sandwich_islands: 🇬🇸
ab :south_sudan: 🇸🇸
ab :sri_lanka: 🇱🇰
ab :st_barthelemy: 🇧🇱
ab :st_helena: 🇸🇭
ab :st_kitts_nevis: 🇰🇳
ab :st_lucia: 🇱🇨
ab :st_martin: 🇲🇫
ab :st_pierre_miquelon: 🇵🇲
ab :st_vincent_grenadines: 🇻🇨
ab :sudan: 🇸🇩
ab :suriname: 🇸🇷
ab :svalbard_jan_mayen: 🇸🇯
ab :swaziland: 🇸🇿
ab :sweden: 🇸🇪
ab :switzerland: 🇨🇭
ab :syria: 🇸🇾
ab :taiwan: 🇹🇼
ab :tajikistan: 🇹🇯
ab :tanzania: 🇹🇿
ab :thailand: 🇹🇭
ab :timor_leste: 🇹🇱
ab :togo: 🇹🇬
ab :tokelau: 🇹🇰
ab :tonga: 🇹🇴
ab :tr: 🇹🇷
ab :transgender_flag: 🏳️‍⚧️
ab :triangular_flag_on_post: 🚩
ab :trinidad_tobago: 🇹🇹
ab :tristan_da_cunha: 🇹🇦
ab :tunisia: 🇹🇳
ab :turkmenistan: 🇹🇲
ab :turks_caicos_islands: 🇹🇨
ab :tuvalu: 🇹🇻
ab :uganda: 🇺🇬
ab :uk: 🇬🇧
ab :ukraine: 🇺🇦
ab :united_arab_emirates: 🇦🇪
ab :united_nations: 🇺🇳
ab :uruguay: 🇺🇾
ab :us: 🇺🇸
ab :us_outlying_islands: 🇺🇲
ab :us_virgin_islands: 🇻🇮
ab :uzbekistan: 🇺🇿
ab :vanuatu: 🇻🇺
ab :vatican_city: 🇻🇦
ab :venezuela: 🇻🇪
ab :vietnam: 🇻🇳
ab :wales: 🏴󠁧󠁢󠁷󠁬󠁳󠁿
ab :wallis_futuna: 🇼🇫
ab :western_sahara: 🇪🇭
ab :white_flag: 🏳️
ab :yemen: 🇾🇪
ab :zambia: 🇿🇲
ab :zimbabwe: 🇿🇼