ab :amphora: 🏺
ab :apple: 🍎
ab :avocado: 🥑
ab :baby_bottle: 🍼
ab :bacon: 🥓
ab :bagel: 🥯
ab :baguette_bread: 🥖
ab :banana: 🍌
ab :beer: 🍺
ab :beers: 🍻
ab :bell_pepper: 🫑
ab :bento: 🍱
ab :beverage_box: 🧃
ab :birthday: 🎂
ab :blueberries: 🫐
ab :bowl_with_spoon: 🥣
ab :bread: 🍞
ab :broccoli: 🥦
ab :bubble_tea: 🧋
ab :burrito: 🌯
ab :butter: 🧈
ab :cake: 🍰
ab :candy: 🍬
ab :canned_food: 🥫
ab :carrot: 🥕
ab :champagne: 🍾
ab :cheese: 🧀
ab :cherries: 🍒
ab :chestnut: 🌰
ab :chocolate_bar: 🍫
ab :chopsticks: 🥢
ab :clinking_glasses: 🥂
ab :cocktail: 🍸
ab :coconut: 🥥
ab :coffee: ☕
ab :cookie: 🍪
ab :corn: 🌽
ab :crab: 🦀
ab :croissant: 🥐
ab :cucumber: 🥒
ab :cupcake: 🧁
ab :cup_with_straw: 🥤
ab :curry: 🍛
ab :custard: 🍮
ab :cut_of_meat: 🥩
ab :dango: 🍡
ab :doughnut: 🍩
ab :dumpling: 🥟
ab :egg: 🥚
ab :eggplant: 🍆
ab :falafel: 🧆
ab :fish_cake: 🍥
ab :flatbread: 🫓
ab :fondue: 🫕
ab :fork_and_knife: 🍴
ab :fortune_cookie: 🥠
ab :fried_egg: 🍳
ab :fried_shrimp: 🍤
ab :fries: 🍟
ab :garlic: 🧄
ab :grapes: 🍇
ab :green_apple: 🍏
ab :green_salad: 🥗
ab :hamburger: 🍔
ab :hocho: 🔪
ab :honey_pot: 🍯
ab :hotdog: 🌭
ab :hot_pepper: 🌶️
ab :icecream: 🍦
ab :ice_cream: 🍨
ab :ice_cube: 🧊
ab :kiwi_fruit: 🥝
ab :knife: 🔪
ab :leafy_green: 🥬
ab :lemon: 🍋
ab :lobster: 🦞
ab :lollipop: 🍭
ab :mandarin: 🍊
ab :mango: 🥭
ab :mate: 🧉
ab :meat_on_bone: 🍖
ab :melon: 🍈
ab :milk_glass: 🥛
ab :moon_cake: 🥮
ab :mushroom: 🍄
ab :oden: 🍢
ab :olive: 🫒
ab :onion: 🧅
ab :orange: 🍊
ab :oyster: 🦪
ab :pancakes: 🥞
ab :peach: 🍑
ab :peanuts: 🥜
ab :pear: 🍐
ab :pie: 🥧
ab :pineapple: 🍍
ab :pizza: 🍕
ab :plate_with_cutlery: 🍽️
ab :popcorn: 🍿
ab :potato: 🥔
ab :poultry_leg: 🍗
ab :pretzel: 🥨
ab :ramen: 🍜
ab :rice: 🍚
ab :rice_ball: 🍙
ab :rice_cracker: 🍘
ab :sake: 🍶
ab :salt: 🧂
ab :sandwich: 🥪
ab :shallow_pan_of_food: 🥘
ab :shaved_ice: 🍧
ab :shrimp: 🦐
ab :spaghetti: 🍝
ab :spoon: 🥄
ab :squid: 🦑
ab :stew: 🍲
ab :strawberry: 🍓
ab :stuffed_flatbread: 🥙
ab :sushi: 🍣
ab :sweet_potato: 🍠
ab :taco: 🌮
ab :takeout_box: 🥡
ab :tamale: 🫔
ab :tangerine: 🍊
ab :tea: 🍵
ab :teapot: 🫖
ab :tomato: 🍅
ab :tropical_drink: 🍹
ab :tumbler_glass: 🥃
ab :waffle: 🧇
ab :watermelon: 🍉
ab :wine_glass: 🍷