ab :abacus: 🧮
ab :accordion: 🪗
ab :adhesive_bandage: 🩹
ab :alembic: ⚗️
ab :athletic_shoe: 👟
ab :axe: 🪓
ab :balance_scale: ⚖️
ab :ballet_shoes: 🩰
ab :ballot_box: 🗳️
ab :banjo: 🪕
ab :bar_chart: 📊
ab :basket: 🧺
ab :bathtub: 🛁
ab :battery: 🔋
ab :bed: 🛏️
ab :bell: 🔔
ab :bikini: 👙
ab :billed_cap: 🧢
ab :black_nib: ✒️
ab :blue_book: 📘
ab :book: 📖
ab :bookmark: 🔖
ab :bookmark_tabs: 📑
ab :books: 📚
ab :boomerang: 🪃
ab :boot: 👢
ab :bow_and_arrow: 🏹
ab :briefcase: 💼
ab :broom: 🧹
ab :bucket: 🪣
ab :bulb: 💡
ab :calendar: 📆
ab :calling: 📲
ab :camera: 📷
ab :camera_flash: 📸
ab :candle: 🕯️
ab :card_file_box: 🗃️
ab :card_index: 📇
ab :card_index_dividers: 🗂️
ab :carpentry_saw: 🪚
ab :cd: 💿
ab :chains: ⛓️
ab :chair: 🪑
ab :chart: 💹
ab :chart_with_downwards_trend: 📉
ab :chart_with_upwards_trend: 📈
ab :clamp: 🗜️
ab :clapper: 🎬
ab :clipboard: 📋
ab :closed_book: 📕
ab :closed_lock_with_key: 🔐
ab :coat: 🧥
ab :coffin: ⚰️
ab :coin: 🪙
ab :computer: 💻
ab :computer_mouse: 🖱️
ab :control_knobs: 🎛️
ab :couch_and_lamp: 🛋️
ab :crayon: 🖍️
ab :credit_card: 💳
ab :crossed_swords: ⚔️
ab :crown: 👑
ab :dagger: 🗡️
ab :dark_sunglasses: 🕶️
ab :date: 📅
ab :desktop_computer: 🖥️
ab :diya_lamp: 🪔
ab :dna: 🧬
ab :dollar: 💵
ab :door: 🚪
ab :dress: 👗
ab :drop_of_blood: 🩸
ab :drum: 🥁
ab :dvd: 📀
ab :e-mail: 📧
ab :electric_plug: 🔌
ab :elevator: 🛗
ab :email: 📧
ab :envelope: ✉️
ab :envelope_with_arrow: 📩
ab :euro: 💶
ab :eyeglasses: 👓
ab :fax: 📠
ab :file_cabinet: 🗄️
ab :file_folder: 📁
ab :film_projector: 📽️
ab :film_strip: 🎞️
ab :fire_extinguisher: 🧯
ab :flashlight: 🔦
ab :flat_shoe: 🥿
ab :floppy_disk: 💾
ab :fountain_pen: 🖋️
ab :funeral_urn: ⚱️
ab :gear: ⚙️
ab :gem: 💎
ab :gloves: 🧤
ab :goggles: 🥽
ab :green_book: 📗
ab :guitar: 🎸
ab :gun: 🔫
ab :hammer: 🔨
ab :hammer_and_pick: ⚒️
ab :hammer_and_wrench: 🛠️
ab :handbag: 👜
ab :headphones: 🎧
ab :headstone: 🪦
ab :high_heel: 👠
ab :hiking_boot: 🥾
ab :hook: 🪝
ab :inbox_tray: 📥
ab :incoming_envelope: 📨
ab :iphone: 📱
ab :izakaya_lantern: 🏮
ab :jeans: 👖
ab :key: 🔑
ab :keyboard: ⌨️
ab :kimono: 👘
ab :label: 🏷️
ab :lab_coat: 🥼
ab :ladder: 🪜
ab :lantern: 🏮
ab :ledger: 📒
ab :level_slider: 🎚️
ab :link: 🔗
ab :lipstick: 💄
ab :lock: 🔒
ab :lock_with_ink_pen: 🔏
ab :long_drum: 🪘
ab :lotion_bottle: 🧴
ab :loudspeaker: 📢
ab :loud_sound: 🔊
ab :mag: 🔍
ab :magnet: 🧲
ab :mag_right: 🔎
ab :mailbox: 📫
ab :mailbox_closed: 📪
ab :mailbox_with_mail: 📬
ab :mailbox_with_no_mail: 📭
ab :mans_shoe: 👞
ab :mega: 📣
ab :memo: 📝
ab :microphone: 🎤
ab :microscope: 🔬
ab :military_helmet: 🪖
ab :minidisc: 💽
ab :mirror: 🪞
ab :moneybag: 💰
ab :money_with_wings: 💸
ab :mortar_board: 🎓
ab :mouse_trap: 🪤
ab :movie_camera: 🎥
ab :moyai: 🗿
ab :musical_keyboard: 🎹
ab :musical_note: 🎵
ab :musical_score: 🎼
ab :mute: 🔇
ab :necktie: 👔
ab :newspaper: 📰
ab :newspaper_roll: 🗞️
ab :notebook: 📓
ab :notebook_with_decorative_cover: 📔
ab :notes: 🎶
ab :no_bell: 🔕
ab :nut_and_bolt: 🔩
ab :old_key: 🗝️
ab :one_piece_swimsuit: 🩱
ab :open_book: 📖
ab :open_file_folder: 📂
ab :orange_book: 📙
ab :outbox_tray: 📤
ab :package: 📦
ab :pager: 📟
ab :page_facing_up: 📄
ab :page_with_curl: 📃
ab :paintbrush: 🖌️
ab :paperclip: 📎
ab :paperclips: 🖇️
ab :pen: 🖊️
ab :pencil: 📝
ab :pencil2: ✏️
ab :petri_dish: 🧫
ab :phone: ☎️
ab :pick: ⛏️
ab :pill: 💊
ab :placard: 🪧
ab :plunger: 🪠
ab :postal_horn: 📯
ab :postbox: 📮
ab :pouch: 👝
ab :pound: 💷
ab :prayer_beads: 📿
ab :printer: 🖨️
ab :probing_cane: 🦯
ab :purse: 👛
ab :pushpin: 📌
ab :radio: 📻
ab :razor: 🪒
ab :receipt: 🧾
ab :rescue_worker_helmet: ⛑️
ab :ring: 💍
ab :roll_of_paper: 🧻
ab :round_pushpin: 📍
ab :safety_pin: 🧷
ab :safety_vest: 🦺
ab :sandal: 👡
ab :sari: 🥻
ab :satellite: 📡
ab :saxophone: 🎷
ab :scarf: 🧣
ab :school_satchel: 🎒
ab :scissors: ✂️
ab :screwdriver: 🪛
ab :scroll: 📜
ab :shield: 🛡️
ab :shirt: 👕
ab :shoe: 👞
ab :shopping: 🛍️
ab :shopping_cart: 🛒
ab :shorts: 🩳
ab :shower: 🚿
ab :smoking: 🚬
ab :soap: 🧼
ab :socks: 🧦
ab :sound: 🔉
ab :speaker: 🔈
ab :spiral_calendar: 🗓️
ab :spiral_notepad: 🗒️
ab :sponge: 🧽
ab :stethoscope: 🩺
ab :straight_ruler: 📏
ab :studio_microphone: 🎙️
ab :swim_brief: 🩲
ab :syringe: 💉
ab :telephone: ☎️
ab :telephone_receiver: 📞
ab :telescope: 🔭
ab :test_tube: 🧪
ab :thong_sandal: 🩴
ab :toilet: 🚽
ab :toolbox: 🧰
ab :toothbrush: 🪥
ab :tophat: 🎩
ab :trackball: 🖲️
ab :triangular_ruler: 📐
ab :trumpet: 🎺
ab :tshirt: 👕
ab :tv: 📺
ab :unlock: 🔓
ab :vhs: 📼
ab :video_camera: 📹
ab :violin: 🎻
ab :wastebasket: 🗑️
ab :window: 🪟
ab :womans_clothes: 👚
ab :womans_hat: 👒
ab :wrench: 🔧
ab :yen: 💴