ab :+1: 👍
ab :-1: 👎
ab :adult: 🧑
ab :anatomical_heart: 🫀
ab :angel: 👼
ab :artist: 🧑‍🎨
ab :astronaut: 🧑‍🚀
ab :baby: 👶
ab :bald_man: 👨‍🦲
ab :bald_woman: 👩‍🦲
ab :basketball_man: ⛹️‍♂️
ab :basketball_woman: ⛹️‍♀️
ab :bath: 🛀
ab :bearded_person: 🧔
ab :bicyclist: 🚴
ab :biking_man: 🚴‍♂️
ab :biking_woman: 🚴‍♀️
ab :blonde_woman: 👱‍♀️
ab :blond_haired_man: 👱‍♂️
ab :blond_haired_person: 👱
ab :blond_haired_woman: 👱‍♀️
ab :bone: 🦴
ab :bouncing_ball_man: ⛹️‍♂️
ab :bouncing_ball_person: ⛹️
ab :bouncing_ball_woman: ⛹️‍♀️
ab :bow: 🙇
ab :bowing_man: 🙇‍♂️
ab :bowing_woman: 🙇‍♀️
ab :boy: 👦
ab :brain: 🧠
ab :breast_feeding: 🤱
ab :bride_with_veil: 👰‍♀️
ab :business_suit_levitating: 🕴️
ab :busts_in_silhouette: 👥
ab :bust_in_silhouette: 👤
ab :call_me_hand: 🤙
ab :cartwheeling: 🤸
ab :child: 🧒
ab :clap: 👏
ab :climbing: 🧗
ab :climbing_man: 🧗‍♂️
ab :climbing_woman: 🧗‍♀️
ab :construction_worker: 👷
ab :construction_worker_man: 👷‍♂️
ab :construction_worker_woman: 👷‍♀️
ab :cook: 🧑‍🍳
ab :cop: 👮
ab :couple: 👫
ab :couplekiss: 💏
ab :couplekiss_man_man: 👨‍❤️‍💋‍👨
ab :couplekiss_man_woman: 👩‍❤️‍💋‍👨
ab :couplekiss_woman_woman: 👩‍❤️‍💋‍👩
ab :couple_with_heart: 💑
ab :couple_with_heart_man_man: 👨‍❤️‍👨
ab :couple_with_heart_woman_man: 👩‍❤️‍👨
ab :couple_with_heart_woman_woman: 👩‍❤️‍👩
ab :crossed_fingers: 🤞
ab :curly_haired_man: 👨‍🦱
ab :curly_haired_woman: 👩‍🦱
ab :dancer: 💃
ab :dancers: 👯
ab :dancing_men: 👯‍♂️
ab :dancing_women: 👯‍♀️
ab :deaf_man: 🧏‍♂️
ab :deaf_person: 🧏
ab :deaf_woman: 🧏‍♀️
ab :detective: 🕵️
ab :ear: 👂
ab :ear_with_hearing_aid: 🦻
ab :elf: 🧝
ab :elf_man: 🧝‍♂️
ab :elf_woman: 🧝‍♀️
ab :eye: 👁️
ab :eyes: 👀
ab :facepalm: 🤦
ab :facepunch: 👊
ab :factory_worker: 🧑‍🏭
ab :fairy: 🧚
ab :fairy_man: 🧚‍♂️
ab :fairy_woman: 🧚‍♀️
ab :family: 👪
ab :family_man_boy: 👨‍👦
ab :family_man_boy_boy: 👨‍👦‍👦
ab :family_man_girl: 👨‍👧
ab :family_man_girl_boy: 👨‍👧‍👦
ab :family_man_girl_girl: 👨‍👧‍👧
ab :family_man_man_boy: 👨‍👨‍👦
ab :family_man_man_boy_boy: 👨‍👨‍👦‍👦
ab :family_man_man_girl: 👨‍👨‍👧
ab :family_man_man_girl_boy: 👨‍👨‍👧‍👦
ab :family_man_man_girl_girl: 👨‍👨‍👧‍👧
ab :family_man_woman_boy: 👨‍👩‍👦
ab :family_man_woman_boy_boy: 👨‍👩‍👦‍👦
ab :family_man_woman_girl: 👨‍👩‍👧
ab :family_man_woman_girl_boy: 👨‍👩‍👧‍👦
ab :family_man_woman_girl_girl: 👨‍👩‍👧‍👧
ab :family_woman_boy: 👩‍👦
ab :family_woman_boy_boy: 👩‍👦‍👦
ab :family_woman_girl: 👩‍👧
ab :family_woman_girl_boy: 👩‍👧‍👦
ab :family_woman_girl_girl: 👩‍👧‍👧
ab :family_woman_woman_boy: 👩‍👩‍👦
ab :family_woman_woman_boy_boy: 👩‍👩‍👦‍👦
ab :family_woman_woman_girl: 👩‍👩‍👧
ab :family_woman_woman_girl_boy: 👩‍👩‍👧‍👦
ab :family_woman_woman_girl_girl: 👩‍👩‍👧‍👧
ab :farmer: 🧑‍🌾
ab :female_detective: 🕵️‍♀️
ab :firefighter: 🧑‍🚒
ab :fist: ✊
ab :fist_left: 🤛
ab :fist_oncoming: 👊
ab :fist_raised: ✊
ab :fist_right: 🤜
ab :foot: 🦶
ab :footprints: 👣
ab :frowning_man: 🙍‍♂️
ab :frowning_person: 🙍
ab :frowning_woman: 🙍‍♀️
ab :fu: 🖕
ab :genie: 🧞
ab :genie_man: 🧞‍♂️
ab :genie_woman: 🧞‍♀️
ab :girl: 👧
ab :golfing: 🏌️
ab :golfing_man: 🏌️‍♂️
ab :golfing_woman: 🏌️‍♀️
ab :guard: 💂
ab :guardsman: 💂‍♂️
ab :guardswoman: 💂‍♀️
ab :haircut: 💇
ab :haircut_man: 💇‍♂️
ab :haircut_woman: 💇‍♀️
ab :hand: ✋
ab :handball_person: 🤾
ab :handshake: 🤝
ab :health_worker: 🧑‍⚕️
ab :horse_racing: 🏇
ab :information_desk_person: 💁
ab :judge: 🧑‍⚖️
ab :juggling_person: 🤹
ab :kneeling_man: 🧎‍♂️
ab :kneeling_person: 🧎
ab :kneeling_woman: 🧎‍♀️
ab :leg: 🦵
ab :lips: 👄
ab :lotus_position: 🧘
ab :lotus_position_man: 🧘‍♂️
ab :lotus_position_woman: 🧘‍♀️
ab :love_you_gesture: 🤟
ab :lungs: 🫁
ab :mage: 🧙
ab :mage_man: 🧙‍♂️
ab :mage_woman: 🧙‍♀️
ab :male_detective: 🕵️‍♂️
ab :man: 👨
ab :man_artist: 👨‍🎨
ab :man_astronaut: 👨‍🚀
ab :man_beard: 🧔‍♂️
ab :man_cartwheeling: 🤸‍♂️
ab :man_cook: 👨‍🍳
ab :man_dancing: 🕺
ab :man_facepalming: 🤦‍♂️
ab :man_factory_worker: 👨‍🏭
ab :man_farmer: 👨‍🌾
ab :man_feeding_baby: 👨‍🍼
ab :man_firefighter: 👨‍🚒
ab :man_health_worker: 👨‍⚕️
ab :man_in_manual_wheelchair: 👨‍🦽
ab :man_in_motorized_wheelchair: 👨‍🦼
ab :man_in_tuxedo: 🤵‍♂️
ab :man_judge: 👨‍⚖️
ab :man_juggling: 🤹‍♂️
ab :man_mechanic: 👨‍🔧
ab :man_office_worker: 👨‍💼
ab :man_pilot: 👨‍✈️
ab :man_playing_handball: 🤾‍♂️
ab :man_playing_water_polo: 🤽‍♂️
ab :man_scientist: 👨‍🔬
ab :man_shrugging: 🤷‍♂️
ab :man_singer: 👨‍🎤
ab :man_student: 👨‍🎓
ab :man_teacher: 👨‍🏫
ab :man_technologist: 👨‍💻
ab :man_with_gua_pi_mao: 👲
ab :man_with_probing_cane: 👨‍🦯
ab :man_with_turban: 👳‍♂️
ab :man_with_veil: 👰‍♂️
ab :massage: 💆
ab :massage_man: 💆‍♂️
ab :massage_woman: 💆‍♀️
ab :mechanic: 🧑‍🔧
ab :mechanical_arm: 🦾
ab :mechanical_leg: 🦿
ab :men_wrestling: 🤼‍♂️
ab :mermaid: 🧜‍♀️
ab :merman: 🧜‍♂️
ab :merperson: 🧜
ab :metal: 🤘
ab :middle_finger: 🖕
ab :mountain_bicyclist: 🚵
ab :mountain_biking_man: 🚵‍♂️
ab :mountain_biking_woman: 🚵‍♀️
ab :mrs_claus: 🤶
ab :muscle: 💪
ab :mx_claus: 🧑‍🎄
ab :nail_care: 💅
ab :ng_man: 🙅‍♂️
ab :ng_woman: 🙅‍♀️
ab :ninja: 🥷
ab :nose: 👃
ab :no_good: 🙅
ab :no_good_man: 🙅‍♂️
ab :no_good_woman: 🙅‍♀️
ab :office_worker: 🧑‍💼
ab :ok_hand: 👌
ab :ok_man: 🙆‍♂️
ab :ok_person: 🙆
ab :ok_woman: 🙆‍♀️
ab :older_adult: 🧓
ab :older_man: 👴
ab :older_woman: 👵
ab :open_hands: 👐
ab :palms_up_together: 🤲
ab :people_holding_hands: 🧑‍🤝‍🧑
ab :people_hugging: 🫂
ab :person_bald: 🧑‍🦲
ab :person_curly_hair: 🧑‍🦱
ab :person_feeding_baby: 🧑‍🍼
ab :person_fencing: 🤺
ab :person_in_manual_wheelchair: 🧑‍🦽
ab :person_in_motorized_wheelchair: 🧑‍🦼
ab :person_in_tuxedo: 🤵
ab :person_red_hair: 🧑‍🦰
ab :person_white_hair: 🧑‍🦳
ab :person_with_probing_cane: 🧑‍🦯
ab :person_with_turban: 👳
ab :person_with_veil: 👰
ab :pilot: 🧑‍✈️
ab :pinched_fingers: 🤌
ab :pinching_hand: 🤏
ab :point_down: 👇
ab :point_left: 👈
ab :point_right: 👉
ab :point_up: ☝️
ab :point_up_2: 👆
ab :policeman: 👮‍♂️
ab :policewoman: 👮‍♀️
ab :police_officer: 👮
ab :pouting_face: 🙎
ab :pouting_man: 🙎‍♂️
ab :pouting_woman: 🙎‍♀️
ab :pray: 🙏
ab :pregnant_woman: 🤰
ab :prince: 🤴
ab :princess: 👸
ab :punch: 👊
ab :raised_back_of_hand: 🤚
ab :raised_hand: ✋
ab :raised_hands: 🙌
ab :raised_hand_with_fingers_splayed: 🖐️
ab :raising_hand: 🙋
ab :raising_hand_man: 🙋‍♂️
ab :raising_hand_woman: 🙋‍♀️
ab :red_haired_man: 👨‍🦰
ab :red_haired_woman: 👩‍🦰
ab :rowboat: 🚣
ab :rowing_man: 🚣‍♂️
ab :rowing_woman: 🚣‍♀️
ab :runner: 🏃
ab :running: 🏃
ab :running_man: 🏃‍♂️
ab :running_woman: 🏃‍♀️
ab :santa: 🎅
ab :sassy_man: 💁‍♂️
ab :sassy_woman: 💁‍♀️
ab :sauna_man: 🧖‍♂️
ab :sauna_person: 🧖
ab :sauna_woman: 🧖‍♀️
ab :scientist: 🧑‍🔬
ab :selfie: 🤳
ab :shrug: 🤷
ab :singer: 🧑‍🎤
ab :skier: ⛷️
ab :sleeping_bed: 🛌
ab :snowboarder: 🏂
ab :speaking_head: 🗣️
ab :standing_man: 🧍‍♂️
ab :standing_person: 🧍
ab :standing_woman: 🧍‍♀️
ab :student: 🧑‍🎓
ab :superhero: 🦸
ab :superhero_man: 🦸‍♂️
ab :superhero_woman: 🦸‍♀️
ab :supervillain: 🦹
ab :supervillain_man: 🦹‍♂️
ab :supervillain_woman: 🦹‍♀️
ab :surfer: 🏄
ab :surfing_man: 🏄‍♂️
ab :surfing_woman: 🏄‍♀️
ab :swimmer: 🏊
ab :swimming_man: 🏊‍♂️
ab :swimming_woman: 🏊‍♀️
ab :teacher: 🧑‍🏫
ab :technologist: 🧑‍💻
ab :thumbsdown: 👎
ab :thumbsup: 👍
ab :tipping_hand_man: 💁‍♂️
ab :tipping_hand_person: 💁
ab :tipping_hand_woman: 💁‍♀️
ab :tongue: 👅
ab :tooth: 🦷
ab :two_men_holding_hands: 👬
ab :two_women_holding_hands: 👭
ab :v: ✌️
ab :vampire: 🧛
ab :vampire_man: 🧛‍♂️
ab :vampire_woman: 🧛‍♀️
ab :vulcan_salute: 🖖
ab :walking: 🚶
ab :walking_man: 🚶‍♂️
ab :walking_woman: 🚶‍♀️
ab :water_polo: 🤽
ab :wave: 👋
ab :weight_lifting: 🏋️
ab :weight_lifting_man: 🏋️‍♂️
ab :weight_lifting_woman: 🏋️‍♀️
ab :white_haired_man: 👨‍🦳
ab :white_haired_woman: 👩‍🦳
ab :woman: 👩
ab :woman_artist: 👩‍🎨
ab :woman_astronaut: 👩‍🚀
ab :woman_beard: 🧔‍♀️
ab :woman_cartwheeling: 🤸‍♀️
ab :woman_cook: 👩‍🍳
ab :woman_dancing: 💃
ab :woman_facepalming: 🤦‍♀️
ab :woman_factory_worker: 👩‍🏭
ab :woman_farmer: 👩‍🌾
ab :woman_feeding_baby: 👩‍🍼
ab :woman_firefighter: 👩‍🚒
ab :woman_health_worker: 👩‍⚕️
ab :woman_in_manual_wheelchair: 👩‍🦽
ab :woman_in_motorized_wheelchair: 👩‍🦼
ab :woman_in_tuxedo: 🤵‍♀️
ab :woman_judge: 👩‍⚖️
ab :woman_juggling: 🤹‍♀️
ab :woman_mechanic: 👩‍🔧
ab :woman_office_worker: 👩‍💼
ab :woman_pilot: 👩‍✈️
ab :woman_playing_handball: 🤾‍♀️
ab :woman_playing_water_polo: 🤽‍♀️
ab :woman_scientist: 👩‍🔬
ab :woman_shrugging: 🤷‍♀️
ab :woman_singer: 👩‍🎤
ab :woman_student: 👩‍🎓
ab :woman_teacher: 👩‍🏫
ab :woman_technologist: 👩‍💻
ab :woman_with_headscarf: 🧕
ab :woman_with_probing_cane: 👩‍🦯
ab :woman_with_turban: 👳‍♀️
ab :woman_with_veil: 👰‍♀️
ab :women_wrestling: 🤼‍♀️
ab :wrestling: 🤼
ab :writing_hand: ✍️
ab :zombie: 🧟
ab :zombie_man: 🧟‍♂️
ab :zombie_woman: 🧟‍♀️