ab :100: 💯
ab :alien: 👽
ab :anger: 💢
ab :angry: 😠
ab :anguished: 😧
ab :astonished: 😲
ab :black_heart: 🖤
ab :blue_heart: 💙
ab :blush: 😊
ab :bomb: 💣
ab :boom: 💥
ab :broken_heart: 💔
ab :brown_heart: 🤎
ab :clown_face: 🤡
ab :cold_face: 🥶
ab :cold_sweat: 😰
ab :collision: 💥
ab :confounded: 😖
ab :confused: 😕
ab :cowboy_hat_face: 🤠
ab :cry: 😢
ab :crying_cat_face: 😿
ab :cupid: 💘
ab :cursing_face: 🤬
ab :dash: 💨
ab :disappointed: 😞
ab :disappointed_relieved: 😥
ab :disguised_face: 🥸
ab :dizzy: 💫
ab :dizzy_face: 😵
ab :drooling_face: 🤤
ab :exploding_head: 🤯
ab :expressionless: 😑
ab :eye_speech_bubble: 👁️‍🗨️
ab :face_exhaling: 😮‍💨
ab :face_in_clouds: 😶‍🌫️
ab :face_with_head_bandage: 🤕
ab :face_with_spiral_eyes: 😵‍💫
ab :face_with_thermometer: 🤒
ab :fearful: 😨
ab :flushed: 😳
ab :frowning: 😦
ab :frowning_face: ☹️
ab :ghost: 👻
ab :gift_heart: 💝
ab :green_heart: 💚
ab :grimacing: 😬
ab :grin: 😁
ab :grinning: 😀
ab :hand_over_mouth: 🤭
ab :hankey: 💩
ab :heart: ❤️
ab :heartbeat: 💓
ab :heartpulse: 💗
ab :heart_decoration: 💟
ab :heart_eyes: 😍
ab :heart_eyes_cat: 😻
ab :heart_on_fire: ❤️‍🔥
ab :hear_no_evil: 🙉
ab :heavy_heart_exclamation: ❣️
ab :hole: 🕳️
ab :hot_face: 🥵
ab :hugs: 🤗
ab :hushed: 😯
ab :imp: 👿
ab :innocent: 😇
ab :japanese_goblin: 👺
ab :japanese_ogre: 👹
ab :joy: 😂
ab :joy_cat: 😹
ab :kiss: 💋
ab :kissing: 😗
ab :kissing_cat: 😽
ab :kissing_closed_eyes: 😚
ab :kissing_heart: 😘
ab :kissing_smiling_eyes: 😙
ab :laughing: 😆
ab :left_speech_bubble: 🗨️
ab :love_letter: 💌
ab :lying_face: 🤥
ab :mask: 😷
ab :mending_heart: ❤️‍🩹
ab :money_mouth_face: 🤑
ab :monocle_face: 🧐
ab :nauseated_face: 🤢
ab :nerd_face: 🤓
ab :neutral_face: 😐
ab :no_mouth: 😶
ab :open_mouth: 😮
ab :orange_heart: 🧡
ab :partying_face: 🥳
ab :pensive: 😔
ab :persevere: 😣
ab :pleading_face: 🥺
ab :poop: 💩
ab :pout: 😡
ab :pouting_cat: 😾
ab :purple_heart: 💜
ab :rage: 😡
ab :raised_eyebrow: 🤨
ab :relaxed: ☺️
ab :relieved: 😌
ab :revolving_hearts: 💞
ab :right_anger_bubble: 🗯️
ab :robot: 🤖
ab :rofl: 🤣
ab :roll_eyes: 🙄
ab :satisfied: 😆
ab :scream: 😱
ab :scream_cat: 🙀
ab :see_no_evil: 🙈
ab :shit: 💩
ab :shushing_face: 🤫
ab :skull: 💀
ab :skull_and_crossbones: ☠️
ab :sleeping: 😴
ab :sleepy: 😪
ab :slightly_frowning_face: 🙁
ab :slightly_smiling_face: 🙂
ab :smile: 😄
ab :smiley: 😃
ab :smiley_cat: 😺
ab :smile_cat: 😸
ab :smiling_face_with_tear: 🥲
ab :smiling_face_with_three_hearts: 🥰
ab :smiling_imp: 😈
ab :smirk: 😏
ab :smirk_cat: 😼
ab :sneezing_face: 🤧
ab :sob: 😭
ab :space_invader: 👾
ab :sparkling_heart: 💖
ab :speak_no_evil: 🙊
ab :speech_balloon: 💬
ab :star_struck: 🤩
ab :stuck_out_tongue: 😛
ab :stuck_out_tongue_closed_eyes: 😝
ab :stuck_out_tongue_winking_eye: 😜
ab :sunglasses: 😎
ab :sweat: 😓
ab :sweat_drops: 💦
ab :sweat_smile: 😅
ab :thinking: 🤔
ab :thought_balloon: 💭
ab :tired_face: 😫
ab :triumph: 😤
ab :two_hearts: 💕
ab :unamused: 😒
ab :upside_down_face: 🙃
ab :vomiting_face: 🤮
ab :weary: 😩
ab :white_heart: 🤍
ab :wink: 😉
ab :woozy_face: 🥴
ab :worried: 😟
ab :yawning_face: 🥱
ab :yellow_heart: 💛
ab :yum: 😋
ab :zany_face: 🤪
ab :zipper_mouth_face: 🤐
ab :zzz: 💤