ab :1234: 🔢
ab :a: 🅰️
ab :ab: 🆎
ab :abc: 🔤
ab :abcd: 🔡
ab :accept: 🉑
ab :aquarius: ♒
ab :aries: ♈
ab :arrows_clockwise: 🔃
ab :arrows_counterclockwise: 🔄
ab :arrow_backward: ◀️
ab :arrow_double_down: ⏬
ab :arrow_double_up: ⏫
ab :arrow_down: ⬇️
ab :arrow_down_small: 🔽
ab :arrow_forward: ▶️
ab :arrow_heading_down: ⤵️
ab :arrow_heading_up: ⤴️
ab :arrow_left: ⬅️
ab :arrow_lower_left: ↙️
ab :arrow_lower_right: ↘️
ab :arrow_right: ➡️
ab :arrow_right_hook: ↪️
ab :arrow_up: ⬆️
ab :arrow_upper_left: ↖️
ab :arrow_upper_right: ↗️
ab :arrow_up_down: ↕️
ab :arrow_up_small: 🔼
ab :asterisk: *️⃣
ab :atm: 🏧
ab :atom_symbol: ⚛️
ab :b: 🅱️
ab :baby_symbol: 🚼
ab :back: 🔙
ab :baggage_claim: 🛄
ab :ballot_box_with_check: ☑️
ab :bangbang: ‼️
ab :beginner: 🔰
ab :biohazard: ☣️
ab :black_circle: ⚫
ab :black_large_square: ⬛
ab :black_medium_small_square: ◾
ab :black_medium_square: ◼️
ab :black_small_square: ▪️
ab :black_square_button: 🔲
ab :blue_square: 🟦
ab :brown_circle: 🟤
ab :brown_square: 🟫
ab :cancer: ♋
ab :capital_abcd: 🔠
ab :capricorn: ♑
ab :children_crossing: 🚸
ab :cinema: 🎦
ab :cl: 🆑
ab :congratulations: ㊗️
ab :cool: 🆒
ab :copyright: ©️
ab :curly_loop: ➰
ab :currency_exchange: 💱
ab :customs: 🛃
ab :diamond_shape_with_a_dot_inside: 💠
ab :do_not_litter: 🚯
ab :eight: 8️⃣
ab :eight_pointed_black_star: ✴️
ab :eight_spoked_asterisk: ✳️
ab :eject_button: ⏏️
ab :end: 🔚
ab :exclamation: ❗
ab :fast_forward: ⏩
ab :female_sign: ♀️
ab :five: 5️⃣
ab :fleur_de_lis: ⚜️
ab :four: 4️⃣
ab :free: 🆓
ab :gemini: ♊
ab :green_circle: 🟢
ab :green_square: 🟩
ab :grey_exclamation: ❕
ab :grey_question: ❔
ab :hash: #️⃣
ab :heavy_check_mark: ✔️
ab :heavy_division_sign: ➗
ab :heavy_dollar_sign: 💲
ab :heavy_exclamation_mark: ❗
ab :heavy_minus_sign: ➖
ab :heavy_multiplication_x: ✖️
ab :heavy_plus_sign: ➕
ab :high_brightness: 🔆
ab :id: 🆔
ab :ideograph_advantage: 🉐
ab :infinity: ♾️
ab :information_source: ℹ️
ab :interrobang: ⁉️
ab :keycap_ten: 🔟
ab :koko: 🈁
ab :large_blue_circle: 🔵
ab :large_blue_diamond: 🔷
ab :large_orange_diamond: 🔶
ab :latin_cross: ✝️
ab :leftwards_arrow_with_hook: ↩️
ab :left_luggage: 🛅
ab :left_right_arrow: ↔️
ab :leo: ♌
ab :libra: ♎
ab :loop: ➿
ab :low_brightness: 🔅
ab :m: Ⓜ️
ab :male_sign: ♂️
ab :medical_symbol: ⚕️
ab :menorah: 🕎
ab :mens: 🚹
ab :mobile_phone_off: 📴
ab :name_badge: 📛
ab :negative_squared_cross_mark: ❎
ab :new: 🆕
ab :next_track_button: ⏭️
ab :ng: 🆖
ab :nine: 9️⃣
ab :non-potable_water: 🚱
ab :no_bicycles: 🚳
ab :no_entry: ⛔
ab :no_entry_sign: 🚫
ab :no_mobile_phones: 📵
ab :no_pedestrians: 🚷
ab :no_smoking: 🚭
ab :o: ⭕
ab :o2: 🅾️
ab :ok: 🆗
ab :om: 🕉️
ab :on: 🔛
ab :one: 1️⃣
ab :ophiuchus: ⛎
ab :orange_circle: 🟠
ab :orange_square: 🟧
ab :orthodox_cross: ☦️
ab :parking: 🅿️
ab :part_alternation_mark: 〽️
ab :passport_control: 🛂
ab :pause_button: ⏸️
ab :peace_symbol: ☮️
ab :pisces: ♓
ab :place_of_worship: 🛐
ab :play_or_pause_button: ⏯️
ab :potable_water: 🚰
ab :previous_track_button: ⏮️
ab :purple_circle: 🟣
ab :purple_square: 🟪
ab :put_litter_in_its_place: 🚮
ab :question: ❓
ab :radioactive: ☢️
ab :radio_button: 🔘
ab :record_button: ⏺️
ab :recycle: ♻️
ab :red_circle: 🔴
ab :red_square: 🟥
ab :registered: ®️
ab :repeat: 🔁
ab :repeat_one: 🔂
ab :restroom: 🚻
ab :rewind: ⏪
ab :sa: 🈂️
ab :sagittarius: ♐
ab :scorpius: ♏
ab :secret: ㊙️
ab :seven: 7️⃣
ab :signal_strength: 📶
ab :six: 6️⃣
ab :six_pointed_star: 🔯
ab :small_blue_diamond: 🔹
ab :small_orange_diamond: 🔸
ab :small_red_triangle: 🔺
ab :small_red_triangle_down: 🔻
ab :soon: 🔜
ab :sos: 🆘
ab :sparkle: ❇️
ab :star_and_crescent: ☪️
ab :star_of_david: ✡️
ab :stop_button: ⏹️
ab :symbols: 🔣
ab :taurus: ♉
ab :three: 3️⃣
ab :tm: ™️
ab :top: 🔝
ab :transgender_symbol: ⚧️
ab :trident: 🔱
ab :twisted_rightwards_arrows: 🔀
ab :two: 2️⃣
ab :u5272: 🈹
ab :u5408: 🈴
ab :u55b6: 🈺
ab :u6307: 🈯
ab :u6708: 🈷️
ab :u6709: 🈶
ab :u6e80: 🈵
ab :u7121: 🈚
ab :u7533: 🈸
ab :u7981: 🈲
ab :u7a7a: 🈳
ab :underage: 🔞
ab :up: 🆙
ab :vibration_mode: 📳
ab :virgo: ♍
ab :vs: 🆚
ab :warning: ⚠️
ab :wavy_dash: 〰️
ab :wc: 🚾
ab :wheelchair: ♿
ab :wheel_of_dharma: ☸️
ab :white_check_mark: ✅
ab :white_circle: ⚪
ab :white_large_square: ⬜
ab :white_medium_small_square: ◽
ab :white_medium_square: ◻️
ab :white_small_square: ▫️
ab :white_square_button: 🔳
ab :womens: 🚺
ab :x: ❌
ab :yellow_circle: 🟡
ab :yellow_square: 🟨
ab :yin_yang: ☯️
ab :zero: 0️⃣