ab :aerial_tramway: 🚡
ab :airplane: ✈️
ab :alarm_clock: ⏰
ab :ambulance: 🚑
ab :anchor: ⚓
ab :articulated_lorry: 🚛
ab :artificial_satellite: 🛰️
ab :auto_rickshaw: 🛺
ab :bank: 🏦
ab :barber: 💈
ab :beach_umbrella: 🏖️
ab :bellhop_bell: 🛎️
ab :bike: 🚲
ab :blue_car: 🚙
ab :boat: ⛵
ab :bricks: 🧱
ab :bridge_at_night: 🌉
ab :building_construction: 🏗️
ab :bullettrain_front: 🚅
ab :bullettrain_side: 🚄
ab :bus: 🚌
ab :busstop: 🚏
ab :camping: 🏕️
ab :canoe: 🛶
ab :car: 🚗
ab :carousel_horse: 🎠
ab :church: ⛪
ab :circus_tent: 🎪
ab :cityscape: 🏙️
ab :city_sunrise: 🌇
ab :city_sunset: 🌆
ab :classical_building: 🏛️
ab :clock1: 🕐
ab :clock10: 🕙
ab :clock1030: 🕥
ab :clock11: 🕚
ab :clock1130: 🕦
ab :clock12: 🕛
ab :clock1230: 🕧
ab :clock130: 🕜
ab :clock2: 🕑
ab :clock230: 🕝
ab :clock3: 🕒
ab :clock330: 🕞
ab :clock4: 🕓
ab :clock430: 🕟
ab :clock5: 🕔
ab :clock530: 🕠
ab :clock6: 🕕
ab :clock630: 🕡
ab :clock7: 🕖
ab :clock730: 🕢
ab :clock8: 🕗
ab :clock830: 🕣
ab :clock9: 🕘
ab :clock930: 🕤
ab :closed_umbrella: 🌂
ab :cloud: ☁️
ab :cloud_with_lightning: 🌩️
ab :cloud_with_lightning_and_rain: ⛈️
ab :cloud_with_rain: 🌧️
ab :cloud_with_snow: 🌨️
ab :comet: ☄️
ab :compass: 🧭
ab :construction: 🚧
ab :convenience_store: 🏪
ab :crescent_moon: 🌙
ab :cyclone: 🌀
ab :department_store: 🏬
ab :derelict_house: 🏚️
ab :desert: 🏜️
ab :desert_island: 🏝️
ab :droplet: 💧
ab :earth_africa: 🌍
ab :earth_americas: 🌎
ab :earth_asia: 🌏
ab :european_castle: 🏰
ab :european_post_office: 🏤
ab :factory: 🏭
ab :ferris_wheel: 🎡
ab :ferry: ⛴️
ab :fire: 🔥
ab :fire_engine: 🚒
ab :first_quarter_moon: 🌓
ab :first_quarter_moon_with_face: 🌛
ab :flight_arrival: 🛬
ab :flight_departure: 🛫
ab :flying_saucer: 🛸
ab :fog: 🌫️
ab :foggy: 🌁
ab :fountain: ⛲
ab :fuelpump: ⛽
ab :full_moon: 🌕
ab :full_moon_with_face: 🌝
ab :globe_with_meridians: 🌐
ab :helicopter: 🚁
ab :hindu_temple: 🛕
ab :hospital: 🏥
ab :hotel: 🏨
ab :hotsprings: ♨️
ab :hourglass: ⌛
ab :hourglass_flowing_sand: ⏳
ab :house: 🏠
ab :houses: 🏘️
ab :house_with_garden: 🏡
ab :hut: 🛖
ab :japan: 🗾
ab :japanese_castle: 🏯
ab :kaaba: 🕋
ab :kick_scooter: 🛴
ab :last_quarter_moon: 🌗
ab :last_quarter_moon_with_face: 🌜
ab :light_rail: 🚈
ab :love_hotel: 🏩
ab :luggage: 🧳
ab :mantelpiece_clock: 🕰️
ab :manual_wheelchair: 🦽
ab :metro: 🚇
ab :milky_way: 🌌
ab :minibus: 🚐
ab :monorail: 🚝
ab :moon: 🌔
ab :mosque: 🕌
ab :motorcycle: 🏍️
ab :motorized_wheelchair: 🦼
ab :motorway: 🛣️
ab :motor_boat: 🛥️
ab :motor_scooter: 🛵
ab :mountain: ⛰️
ab :mountain_cableway: 🚠
ab :mountain_railway: 🚞
ab :mountain_snow: 🏔️
ab :mount_fuji: 🗻
ab :national_park: 🏞️
ab :new_moon: 🌑
ab :new_moon_with_face: 🌚
ab :night_with_stars: 🌃
ab :ocean: 🌊
ab :office: 🏢
ab :oil_drum: 🛢️
ab :oncoming_automobile: 🚘
ab :oncoming_bus: 🚍
ab :oncoming_police_car: 🚔
ab :oncoming_taxi: 🚖
ab :open_umbrella: ☂️
ab :parachute: 🪂
ab :parasol_on_ground: ⛱️
ab :partly_sunny: ⛅
ab :passenger_ship: 🛳️
ab :pickup_truck: 🛻
ab :police_car: 🚓
ab :post_office: 🏣
ab :racing_car: 🏎️
ab :railway_car: 🚃
ab :railway_track: 🛤️
ab :rainbow: 🌈
ab :red_car: 🚗
ab :ringed_planet: 🪐
ab :rock: 🪨
ab :rocket: 🚀
ab :roller_coaster: 🎢
ab :roller_skate: 🛼
ab :rotating_light: 🚨
ab :sailboat: ⛵
ab :school: 🏫
ab :seat: 💺
ab :shinto_shrine: ⛩️
ab :ship: 🚢
ab :skateboard: 🛹
ab :small_airplane: 🛩️
ab :snowflake: ❄️
ab :snowman: ⛄
ab :snowman_with_snow: ☃️
ab :speedboat: 🚤
ab :stadium: 🏟️
ab :star: ⭐
ab :star2: 🌟
ab :stars: 🌠
ab :station: 🚉
ab :statue_of_liberty: 🗽
ab :steam_locomotive: 🚂
ab :stopwatch: ⏱️
ab :stop_sign: 🛑
ab :sunny: ☀️
ab :sunrise: 🌅
ab :sunrise_over_mountains: 🌄
ab :sun_behind_large_cloud: 🌥️
ab :sun_behind_rain_cloud: 🌦️
ab :sun_behind_small_cloud: 🌤️
ab :sun_with_face: 🌞
ab :suspension_railway: 🚟
ab :synagogue: 🕍
ab :taxi: 🚕
ab :tent: ⛺
ab :thermometer: 🌡️
ab :timer_clock: ⏲️
ab :tokyo_tower: 🗼
ab :tornado: 🌪️
ab :tractor: 🚜
ab :traffic_light: 🚥
ab :train: 🚋
ab :train2: 🚆
ab :tram: 🚊
ab :trolleybus: 🚎
ab :truck: 🚚
ab :umbrella: ☔
ab :vertical_traffic_light: 🚦
ab :volcano: 🌋
ab :waning_crescent_moon: 🌘
ab :waning_gibbous_moon: 🌖
ab :watch: ⌚
ab :waxing_crescent_moon: 🌒
ab :waxing_gibbous_moon: 🌔
ab :wedding: 💒
ab :wind_face: 🌬️
ab :wood: 🪵
ab :world_map: 🗺️
ab :zap: ⚡